import {
  Activity,
  Bell,
  Brain,
  ChevronDown,
  ChevronRight,
  Clock,
  Database,
  FileSearch,
  Filter,
  GitBranch,
  HardDrive,
  Key,
  Layers,
  MessageSquare,
  Pencil,
  Plug,
  Plus,
  RefreshCw,
  Search,
  Server,
  Settings,
  Stethoscope,
  Terminal,
  Trash2,
  TrendingUp,
  User,
  Users,
  Webhook,
  Zap,
  X,
  Check,
  AlertTriangle,
  XCircle,
  Power,
  Eye,
  Sparkles,
  Play,
  Pause,
  Download,
  Square,
  Edit,
  Code2,
  BookOpen,
  ExternalLink,
  Copy,
  Bot,
  Loader2,
  AlertCircle,
  Sun,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  activity: Activity,
  bell: Bell,
  brain: Brain,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  clock: Clock,
  database: Database,
  "file-search": FileSearch,
  filter: Filter,
  "git-branch": GitBranch,
  "hard-drive": HardDrive,
  key: Key,
  layers: Layers,
  "message-square": MessageSquare,
  pencil: Pencil,
  plug: Plug,
  plus: Plus,
  refresh: RefreshCw,
  search: Search,
  server: Server,
  settings: Settings,
  stethoscope: Stethoscope,
  terminal: Terminal,
  trash: Trash2,
  "trending-up": TrendingUp,
  user: User,
  users: Users,
  webhook: Webhook,
  zap: Zap,
  x: X,
  check: Check,
  warning: AlertTriangle,
  "x-circle": XCircle,
  power: Power,
  eye: Eye,
  sparkles: Sparkles,
  play: Play,
  pause: Pause,
  download: Download,
  square: Square,
  edit: Edit,
  code: Code2,
  book: BookOpen,
  "external-link": ExternalLink,
  copy: Copy,
  bot: Bot,
  loader: Loader2,
  "alert-circle": AlertCircle,
  sun: Sun,
};

export interface IconProps {
  name: keyof typeof ICON_MAP;
  className?: string;
  size?: number;
  strokeWidth?: number;
}

export function Icon({ name, className, size = 14, strokeWidth = 2 }: IconProps) {
  const Cmp = ICON_MAP[name] ?? Activity;
  return <Cmp size={size} strokeWidth={strokeWidth} className={className} />;
}

export type IconName = keyof typeof ICON_MAP;
